default_language_version:
  python: python3.10.7
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '\.xml$'
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
      - id: fix-encoding-pragma
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
