[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Seth Docherty <sddocherty@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"
cookiecutter = "^2.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
